### ISSUE TITLE
about event after selected

### ISSUE THREAD

**Issue by patcher1983** [timdwilson/typeahead-mvc-model#1]
Hi timdwilson,

it there a event after item seleted?

**Comment by timdwilson** [comment]
Sorry for the delay... for some reason I wasn't notified when this was posted.  Yes, there is an event after the item is selected.  In the typeahead.mvc.model.js file in the Scripts folder, you may add whatever code you need to the function onselected().  This project is meant to get you started with Typeahead and manual changes to the files that I create may be needed for your particular site.  If there's any other way that I can help, please let me know!

**Comment by patcher1983** [comment]
many thanks:)
