### ISSUE TITLE
Doesn't work when model references list item by index

### ISSUE THREAD

**Issue by roryaherne** [timdwilson/typeahead-mvc-model#4]
I posted this on [stackoverflow](https://stackoverflow.com/questions/35587508/using-typeahead-mvc-model-in-dynamically-created-html-autocompletefor) and someone said I should also notify it to you

**Comment by timdwilson** [comment]
Thanks for the head's up. I'll take a look and get back to you.

**Comment by timdwilson** [comment]
Rory, can you please send me your controller (.cs) and view (.cshtml) so I can see the complete example?  Thanks so much!

**Comment by roryaherne** [comment]
[RecipesController.zip](https://github.com/timdwilson/typeahead-mvc-model/files/143460/RecipesController.zip)

I've added you as a collaborator to the project also incase you need anything else.

Thanks for taking the time to look at this.

Rory

**Comment by timdwilson** [comment]
Ok great. Thanks for the source code (and model too :).  Even better that I have access to your project :)  I'll take a look and get back to you soon.

**Comment by timdwilson** [comment]
I'm looking at it. Hopefully I can get you an answer today. If not, I'll let you know.

**Comment by timdwilson** [comment]
Hi Rory, I see what you are talking about after taking a closer look at your project.  I went ahead and updated the source code to do what you are asking.  Thanks for debugging this as far as you did to give me a headstart in the right direction!  Can you please copy the text from this file [HtmlHelpers.cs.txt](https://github.com/timdwilson/typeahead-mvc-model/files/143868/HtmlHelpers.cs.txt) and paste it into the HtmlHelpers.cs file in the Helpers folder and let me know if this fix works for you?

**Comment by timdwilson** [comment]
Oh, and you will also need to update your source code (for now) to this:

`@Html.AutocompleteFor(model => model.SelectedIngredientsNames[i], model => model.SelectedIngredients[i], i, "GetIngredients", "Recipes", false)`

Basically, providing the index to the autocomplete helper function.  I will work on eliminating that for the future but my tests show that this is working for now.

**Comment by roryaherne** [comment]
Hi Tim,

I can confirm this is working for me now. I'll leave closing of the issue to you.

Thanks for your help!

**Comment by timdwilson** [comment]
Thanks Rory! Glad to hear.  I'll include this functionality in the next version of the typeahead-mvc-model nuget package as well.

**Comment by roryaherne** [comment]
Glad I could help.

If you are open to suggestions, may I suggest a htmlAttributes param that can be merged with the one inside the helper? That way then we can add our own classes and perhaps more importantly, our own event handlers.

I've a work around for my own needs (see attached) but I thought an official param might be nice?

[helper.txt](https://github.com/timdwilson/typeahead-mvc-model/files/145405/helper.txt)

**Comment by adamjames** [comment]
Hi Tim, Rory,

+1 for that, would be a very useful addition as I'd already (rather messily
I'm ashamed to admit) done something similar for a project that uses this.

Kind regards,
Adam

**Comment by timdwilson** [comment]
_Re-posting as my email reply did not make it to GitHub_
Hi Adam and Rory,

Interesting that you both should bring this up :)  I just implemented that in v1.0.6.  While I was implementing the changes for Rory, I thought I might as well include that too.  You can specify htmlAttributes in additionalViewData just like you can for other MVC components (e.g. EditorFor).  Yes, that's always been in the back of my mind as something that I need to implement as users of this component are quite handicapped without it lol.  I guess I just assumed that people would implement this themselves if they wanted it but, yet, it can get quite messy!  So, yes, I took the easy way when I first created this package and just hard-coded it in :)  Anyway, all of these changes have been checked into GitHub and published on NuGet.  I tested the updated NuGet package against your code example, Rory, and it does work.

Thanks for the ideas.  Keep them coming!

**Comment by adamjames** [comment]
Fantastic news, thanks Tim!
